language: python
python:
- '3.6'
- nightly
before_install:
- pip install git-pull-request
install:
- pip install .
script:
- python setup.py test
after_success:
- pwd
- env
- git config --list
- git checkout $TRAVIS_BRANCH
- "./pull.sh"
env:
  global:
  - secure: G3leovBC/h3Qa8XzdPEcovwUKjxsHmHoqNKO7nAloYn7sBAFohElND3YKPDeLjUtNd25b36rWYs8PVl+sfWX2gH4ckLSHIH2KcIPeMOu5B9HreRFL/p5fJ09zeF9PnRzapkEAcPyaExQ0orX3dEcai7N+I48kZRi5VFf20wffCdh51tRZQAp+tZtIOsxFLoIba2cS8Q2p6Rv8VLHHEA+1hbEdV5iNPvQzv74L/XaaZqBqCUh3yGGha29iZ6N5LN1VhbzE67xlkOzCveIhKrqIdBF6gMeFgenqhgswS5IIEdSveEW7zvTdgWlZVUsVNUA/rSjp5Bd61P2M7nIhb/yyMkpqogd7Zw4kIhIXSDkrWEK8oBFrdmRW/Sg1KmMZa8lv8hgkEroeWDlKvn52g8YInljGDvsP1dzU4HKvAiOXIhT7TrNo4gMr9HLbVFTliGjFA+5foHYmPT440Rw3JcHkrrUiZFZKmM3bk2j560ANkog0BUFuQ3GdbQLan1WMkm4HQnZVDwLwEBZXB+FzXyQ5wEFKuy2C27/LtV+aDv2St6tldXUfhG27UYmRWfa4YnP6sMYpLvAuBi+u+Iwm4+dYdyL4dcVYyzuzRUQmS0PMltRt6gJ3IpH7p9suwbq3IKnrhiPndwNVWeS1Kjq9MIaB1Nak//kqO4NgjK+MqfBB9Q=
  - secure: X4+ZAP78HwssUjrJ5XsxSflDoj2hmk8g7YSRgS8ot0+Y0EBDJNh6k3WG5dTWAWTiUSqdGs7G0kIpg50kaxbNixwpf0CF12j7892qOfoPW9FF+JBX8Iypue3BT0V/wCeVN/4Qz1gdvu2S1FinI0xEdUGQ6ThNhn1w2FwG7RkT+Z5V7ShGxVPX14MBBdW//Pcl1aM0ggVDZ4IPwb2mnnOivJ8o/Bo8Gu508lOUefENYoT8656Q/E/sZ0Q9ykXJo2srKD0V+s5D1stqLfD61/0wHxB1DqJEdpwpmZFEAZa9hjWwGzZ8K2xC/p/wqu80c2GMr82wvOMz1TKvuUdfPyKNqg8PlWCdiWx5/RKrEznyzbesTFP/M5P8oKkItmqk3d+ev0+cFM8kyF2lH3RSQY8wdopb83t5nbMGQfGfBuryPiIgXp2mY4bl108Z1ZVLyGDe52Gf8TpiznWBC8PxeRFcePeE/B8Z20z5DM+olTQfcZpsQgvV2XwnvzwYp+1Nl5ZGxMRTWDkh2rr/zwpcd3lVVAAqfqVwPK2IR43YmsWE6jQctA0gccuOXA9XtKbe55iRddoFmuKI7fy/62wm3tyJCct52OZiehglUuUiwF3ULMspmwQaqaqEz3mWj/OYigEAqybaqzHgTxQfwKs/xYc1+48IWc/rm0hpHBHXYff7+Ec=
