language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "nightly"  # nightly build
# command to install dependencies
before_install:
  - pip install git-pull-request
install:
  - pip install .
# command to run tests
script:
  - python setup.py test

after_success:
  - pwd
  - env
  - git config --list
  - git checkout $TRAVIS_BRANCH
  - curl -H "Authorization: token  32fc1954d3604f60c1e1e65a7d15ea61bb18f50e -X POST -d "{ \"title\":\"title\",\"head\":\"${TRAVIS_HEAD}\",\"base\":\"master\", \"body\": \"Hello world\", }" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/pulls"
