language: python
python:
- '3.6'
- nightly
before_install:
- pip install git-pull-request
install:
- pip install .
script:
- python setup.py test
after_success:
- pwd
- env
- git config --list
- git checkout $TRAVIS_BRANCH
- "./pull.sh"
env:
  global:
  - secure: ZcyZ+gW2KPhXRtbSLZ6AcmGKVh6Ud3+N372+cmr6VDyHQke3iHH5TdODLXWW/iZbv9GFEGnfAGxn8pSCc4mgR3JZipVr4EdyA7ScgNieufHc5aPKBcdPhHTQ4sn6JNTfAZz7tD0PMmX3uFIOOkVp9Hn7Nj/hIPgFy1I8eGFoDzUTXlED7k/MC3Kcm3gQgnif4qI9nX9gtUpNzLKacpWVpkkgDJLClZMGie1m/YV34h8VScW4trUjsU21895N1k+gi3akvHrmGCYCgx0FTWVJ0EQyn+DyMemgnj/pYmBAPrUtvQeYGYl0PzoOpyhw5yRuoOb/g3klnUgKwVx21V1ZRKGCM5qfeM+1TahdRXkgAjIpyB9FKLirmxkpq5PkdPUT9Vp71gMknA7P/Ida1Jg2xpAhE60mJeTeqgySRFNcRnXMq7bCRT/luSq1olxWL1SzkTMAgpSs9XqXbG42NfClj6fGGr34cJzQ3kAXEcD1SQc8ETb/OT3MTMozs+SI1Z+rwqh0WWfJVkscVqbLQnxZbLnS/zCU1T/tE4mvxIuPSZ/Xyqm2Qh2Jd4Wj6xIpOha62amH3JuYvZ2NAjBEH/j80cprYPDW+UqrnpufQ0Efafwmn2IKQxvBTDvUifD2E5IvgXpbdc0Z8BTkPOCh0fs6MxZmeOgTLk29j8GIdxHTh4o=
  - secure: fwJX9Ktg/hI8YmLGOZNEMbbgru3dIM8MD4lSJJZhYV8/889BRn1Skwe+je7wRGxl4Vis3ZTHwEbAuZK7iyjx/WnXCX7qArU3InOyNv+a+ItJQu0CYdQGljLUFEiKWQfrazM7B555ufT/d4SZEd3lkpAUPI2ymJjt2A3hDIrA7FEdGz9umCDRurAz3YCXFHUze+gtkMKSt56a5RExnAflbd+BCziXi73ocLSAARYXs5xGjur6V/MgJxN1874ON4L4n5U87SUoLOqTvbpZV0AVFIxxbiazRIDuGfaA79h5/Q1sUcY8Fg4RjrBkguT7tHfFQ8KF9fOf8Z+iwnF76uuFDXl9RdwxOh4d9Jhoke/9125CJUrCPWcsWSPBl7DxkMmmIenVI6TRzKXbFjbTE73GJ6lNKZJ3O4w/RUN6Dlewv4PGCh924YHSXzWqPV6hZ8B9SHSy5PVqSQv3K+puhs1tqBFAh7sz/1EMd6sYryX+RD3SC0T/+/2v876LlpXlg1NWpAbsCS7D2ZTVP4BhoMH9IkOf16HTMC9JL4T04oYy353vqRz/B7ufu9b5ljGl23VAd9uOJGWk4nOim/nziHv67DK5B+Hd3MzpIYEs6XcPEAmLCXbAxzSHzygCge3zJkgYncOO8L9UGKLoiI08FyOQctPo6RBUK06HeyaRCnZFjQ0=
  - secure: iD00TzRqM/YGcwVbScMpRdm6J34d3qMLm9UEko4IRlYTzHkTDgElrR/NUTcOy6LwQ8jhSuZSpIuKZwABxs9/Qv5eeHIOSViC2AdhU3ACku51Gc/rgiu0GSUIqylSLu0KMPVJ2e3t+p7P2BgpHcA4h0gmgz3ZU4ooVKvnkXklUhi23+0ZqPdLEXa+hr0Z1/C+LevqxApowlIzJA5Rx1xDT/BEVm4I7/fsZD4KqMGDjHHovtKPw8JFh9+RJww4USH4IO2JWq7wz3zA3d+cZTDYcErtPijWk0fjv5ue19T4dxvf+sj3QM6SncDwPO4OPyHIqgCnB+R6q1TyTJj1nH15ppU5wcH7ZoEGN8QtK8s2zFUNMsHOEam9j3OpfeCxpvQJc3fo6p6ujxQ2PTBewuvb0zOALichWzkQStpRNt1mt45ex09CEvhjDs+lJ15+70icYL7J6fDlFj5NLBtdhyeLh5pruUwV+Elme3gnshO95aYYWGrozLHVThB2HZzgh14F8Fw5KwSVGY0T/c5587JiZZ6Oizwda3X3zug6Nskomo+qGCbFMrCmHZrSndoH0KTDS8SZW1QMZZ+Dlj62r7iBnpLup/l2ikKdCQMPNG9s2hDT8ClhWXZqotV1Fcyml3r5Zv/NA2Amhxe57S0KDCYF9f/Uc46KS2xWaFvWPWTS+pc=
